export {TupleExclude as Exclude} from './Exclude'
export {TupleExtract as Exctract} from './Extract'
export * from './Flatten'
export * from './Insert'
export * from './Join'
export * from './Permutation'
export * from './Slice'
export * from './SubArray'
export * from './SubSequence'
export * from './Tail'