name: PR checks
on:
  pull_request:
    branches: ['main']
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn test